### PR TITLE
operator: patch deployment status instead of update

### PR DESCRIPTION
**Pull request by avalluri**
Update fails if there is any mismatch in resource revision due to
intermediate updates to that deployment. Then the operator has to get
fresh copy and update status on that revision. Instead, we can use
patch.

The same observed in CI test failure:
```
deployment_controller.go:172] failed to update status "Running" for deployment "pmem-csi-with-defaults": Operation cannot be fulfilled on deployments.pmem-csi.intel.com "pmem-csi-with-defaults": the object has been modified; please apply your changes to the latest version and try again
```

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
The change itself looks reasonable, but under which circumstances did that lead to a test failure?

**Comment by pohly** [comment]
Wasn't the code handling this already by fetching the object?

Do we have a test that covers the scenario?

**Comment by avalluri** [comment]
> Wasn't the code handling this already by fetching the object?

Operator fetches the object at the start of reconciling and tries to update the status on the end of it. It misses the updates that happened between these two points. 

> 
> Do we have a test that covers the scenario?

I guess no. This was not visible as the next reconcile updates the status successfully. I will write a test for it.

**Comment by avalluri** [comment]
> The change itself looks reasonable, but under which circumstances did that lead to a test failure?

I am not sure which leads to this, but it was observed in other latest test also:
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/blue/organizations/jenkins/pmem-csi/detail/PR-695/26/tests

**Review by pohly — CHANGES_REQUESTED** [review]
Tests fail. I haven't looked at the updated PR yet.

**Comment by pohly** [comment]
> Tests fail. I haven't looked at the updated PR yet.

Did `Revert "pmem-csi-driver: Unregister node on exit"` fix that or do we have random test failures?

**Comment by pohly** [comment]
https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/job/PR-732/2/ failed because connecting to the node during sanity testing failed.

Please remove my commit, it doesn't belong into this PR.

**Comment by avalluri** [comment]
> > Tests fail. I haven't looked at the updated PR yet.
> 
> Did `Revert "pmem-csi-driver: Unregister node on exit"` fix that or do we have random test failures?

I suspect some random failure. The same random "connection failures in csi sanity tests" observed in #695. Which I am checking now. CSI sanity has 1-minute connection timeout and the controller is busy serving pod scheduler:

```
[2020-09-15T23:03:05.289Z] [BeforeEach] PMEM-CSI
[2020-09-15T23:03:05.289Z]   /mnt/workspace/pmem-csi_PR-695/test/e2e/storage/sanity.go:232
[2020-09-15T23:03:05.289Z] [1mSTEP[0m: connecting to CSI driver
.......
020-09-15T23:03:59.370Z] pmem-csi-govm-worker1:     PID USER      PR  NI    VIRT    RESpmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.485604       1 pmem-csi-driver.go:396] HTTP request: POST "/pod/mutate" from 172.17.0.4:42016 kube-apiserver-admission
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.488238       1 http.go:84] scheduler/webhook "msg"="received request"  "UID"="3ee49bd9-3928-4f58-8abc-2b0de2d970cd" "kind"={"group":"","version":"v1","kind":"Pod"} "resource"={"group":"","version":"v1","resource":"pods"}
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.496273       1 mutate_pod.go:60] mutate pod : PMEM-CSI storage classes map[pmem-csi-sc-cache:false pmem-csi-sc-ext4:false pmem-csi-sc-ext4-kata:true pmem-csi-sc-late-binding:true pmem-csi-sc-xfs:false pmem-csi-sc-xfs-kata:true]
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.496318       1 mutate_pod.go:67] mutate pod : does not use inline or delayed PMEM volumes
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.497734       1 http.go:106] scheduler/webhook "msg"="wrote response" "code"=200 "reason"="no relevant PMEM volumes" "UID"="3ee49bd9-3928-4f58-8abc-2b0de2d970cd" "allowed"=true
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.516983       1 pmem-csi-driver.go:396] HTTP request: POST "/pod/mutate" from 172.17.0.4:42016 kube-apiserver-admission
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.518378       1 http.go:84] scheduler/webhook "msg"="received request"  "UID"="7d991e71-53ad-4af3-a5c5-d9996f65b5c1" "kind"={"group":"","version":"v1","kind":"Pod"} "resource"={"group":"","version":"v1","resource":"pods"}
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.519710       1 mutate_pod.go:60] mutate pod : PMEM-CSI storage classes map[pmem-csi-sc-cache:false pmem-csi-sc-ext4:false pmem-csi-sc-ext4-kata:true pmem-csi-sc-late-binding:true pmem-csi-sc-xfs:false pmem-csi-sc-xfs-kata:true]
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.519827       1 mutate_pod.go:67] mutate pod : does not use inline or delayed PMEM volumes
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.519946       1 http.go:106] scheduler/webhook "msg"="wrote response" "code"=200 "reason"="no relevant PMEM volumes" "UID"="7d991e71-53ad-4af3-a5c5-d9996f65b5c1" "allowed"=true
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.528986       1 pmem-csi-driver.go:396] HTTP request: POST "/pod/mutate" from 172.17.0.4:42018 kube-apiserver-admission
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.531878       1 http.go:84] scheduler/webhook "msg"="received request"  "UID"="37f247fd-0b30-4354-9c42-ffc533b99845" "kind"={"group":"","version":"v1","kind":"Pod"} "resource"={"group":"","version":"v1","resource":"pods"}
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.532826       1 mutate_pod.go:60] mutate pod : PMEM-CSI storage classes map[pmem-csi-sc-cache:false pmem-csi-sc-ext4:false pmem-csi-sc-ext4-kata:true pmem-csi-sc-late-binding:true pmem-csi-sc-xfs:false pmem-csi-sc-xfs-kata:true]
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.533475       1 mutate_pod.go:67] mutate pod : does not use inline or delayed PMEM volumes
[2020-09-15T23:03:59.370Z] pmem-csi-controller-0/pmem-driver@pmem..ster: I0915 23:03:55.533683       1 http.go:106] scheduler/webhook "msg"="wrote response" "code"=200 "reason"="no relevant PMEM volumes" "UID"="37f247fd-0b30-4354-9c42-ffc533b99845" "allowed"=true
```

**Comment by avalluri** [comment]
> https://cloudnative-k8sci.southcentralus.cloudapp.azure.com/job/pmem-csi/view/change-requests/job/PR-732/2/ failed because connecting to the node during sanity testing failed.

Yes, this is what puzzles me. This change is not supposed to change driver behavior at all but surprisingly failed with sanity connection timeouts.
> 
> Please remove my commit, it doesn't belong into this PR.

I will revert.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go [hunk 1]
```diff
@@ -151,6 +152,11 @@ func (r *ReconcileDeployment) Reconcile(request reconcile.Request) (reconcile.Re
 		return reconcile.Result{Requeue: requeue, RequeueAfter: requeueDelayOnError}, err
 	}
 
+	// Temporarily pause reconcile
+	for r.pause {
+		time.Sleep(10 * time.Millisecond)
+	}
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:158]: This approach relies on timing and multiple goroutines. This looks rather fragile to me.

As you have to modify the production code anyway (in this case I really don't see an alternative), why not add some callback mechanism here? Then you can reliably execute some additional test code in the middle of the reconcile.

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/pmem-csi-operator/controller/deployment/controller_driver.go [hunk 2]
```diff
@@ -93,6 +95,9 @@ func (d *PmemCSIDriver) Reconcile(r *ReconcileDeployment) (bool, error) {
 	klog.Infof("Deployment: %q, state %q, changes %v, in cache %v", d.Name, d.Status.Phase, changes, foundInCache)
 
 	requeue, err := d.reconcileDeploymentChanges(r, changes, foundInCache)
+	// Revert any spec changes(like deployment defaults) we made.
+	// Those are not supposed to save on the API server.
+	d.Deployment.Spec = copy.Spec
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/controller_driver.go:100]: Is this still needed?

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go (hunk 1 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:158]: Sounds good. I will change to callback.

File: pkg/pmem-csi-operator/controller/deployment/controller_driver.go (hunk 2 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/controller_driver.go:100]: Yes, it's because all the clients do not support patching status reliability. In the context of unit tests, the test client does not support patching status instead it updates the whole object, which leads to unexpected failures. So to cover all cases we revert spec changes.

**Comment by pohly** [comment]
> I suspect some random failure. The same random "connection failures in csi sanity tests" observed in #695. Which I am checking now. CSI sanity has 1-minute connection timeout and the controller is busy serving pod scheduler

I've also seen it in https://github.com/intel/pmem-csi/pull/723.

I added https://github.com/intel/pmem-csi/pull/723/commits/f1288cda4e618520f83a5103ab1d08e612f61c5a to make it more obvious when the driver installation is unhealthy, but that then just failed during `WaitForPMEMDriver`. Looks like a networking regression in Kubernetes 1.19 to me: we have to enable the `EndpointSlice` feature gate there while it is off in older Kubernetes.

https://github.com/intel/pmem-csi/blob/3222b30f41759a2687b6f3be26567194cbe8ae98/test/test-config.sh#L150-L158

**Comment by pohly** [comment]
>  Looks like a networking regression in Kubernetes 1.19 to me

I'm working on an update to 1.19.1 and also found that it is possible to disable EndpointSlices entirely in 1.19, which I'll do.

**Comment by pohly** [comment]
> I'm working on an update to 1.19.1 and also found that it is possible to disable EndpointSlices entirely in 1.19, which I'll do.

PR #734

**Comment by pohly** [comment]
The code no longer compiles:
```
pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:229:19: undefined: index
```

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go (hunk 1 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:164]: Done. Reconcile hooks are used to validate this case.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go [hunk 3]
```diff
@@ -151,6 +156,13 @@ func (r *ReconcileDeployment) Reconcile(request reconcile.Request) (reconcile.Re
 		return reconcile.Result{Requeue: requeue, RequeueAfter: requeueDelayOnError}, err
 	}
 
+	// Temporarily pause reconcile
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:159]: Out-dated comment.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go [hunk 4]
```diff
@@ -120,6 +124,7 @@ func NewReconcileDeployment(client client.Client, opts pmemcontroller.Controller
 		namespace:      opts.Namespace,
 		containerImage: opts.DriverImage,
 		deployments:    map[string]*pmemcsiv1alpha1.Deployment{},
+		reconcileHooks: []ReconcileHook{},
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:127]: You can drop this initialization.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go [hunk 5]
```diff
@@ -195,6 +208,27 @@ func (r *ReconcileDeployment) EventBroadcaster() record.EventBroadcaster {
 	return r.evBroadcaster
 }
 
+// AddHook adds given reconcile hook to hooks list and returns the
+// an unique id that should be passed while removing the hook
+func (r *ReconcileDeployment) AddHook(h ReconcileHook) int {
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/deployment_controller.go:213]: You don't need the id. Function pointers can be compared and thus RemoveHook can take the same argument as AddHook.

But IMHO this is all overkill. A single pointer is enough for the purpose.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go [hunk 6]
```diff
@@ -494,6 +494,38 @@ func TestDeploymentController(t *testing.T) {
...
+				require.NoError(t, err, "failed to update deployment")
+			}
+			hookId := tc.rc.(*deployment.ReconcileDeployment).AddHook(hook)
+
+			testReconcilePhase(t, tc.rc, tc.c, d.name, false, false, api.DeploymentPhaseRunning)
+			validateDriver(t, tc, dep, []string{api.EventReasonNew, api.EventReasonRunning})
+
+			tc.rc.(*deployment.ReconcileDeployment).RemoveHook(hookId)
+
+			// Next reconcilephase should catch the deployment changes
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:524]: s/reconcilephase/reconcile phase/

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go [hunk 7]
```diff
@@ -626,6 +658,7 @@ func TestDeploymentController(t *testing.T) {
 			err = tc.c.Get(context.TODO(), client.ObjectKey{Name: cm2.Name, Namespace: testNamespace}, cm)
 			require.NoErrorf(t, err, "get '%s' config map after reconcile", cm2.Name)
 		})
+
```
Comment (pohly) [inline pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go:661]: Spurious whitespace change.

File: pkg/pmem-csi-operator/controller/deployment/controller_driver.go (hunk 2 above)
Comment (pohly) [reply pkg/pmem-csi-operator/controller/deployment/controller_driver.go:100]: It would be useful to explain that in the code because it isn't obvious.

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go (hunk 3 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller.go]: Removed.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go (hunk 4 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller.go]: With the latest change, the `reconcileHook`  is a `map`, that requires initialization.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller.go (hunk 5 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller.go]: Made this simple by moving to the map.

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go (hunk 6 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go]: Done

File: pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go (hunk 7 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/deployment_controller_test.go]: Removed.

File: pkg/pmem-csi-operator/controller/deployment/controller_driver.go (hunk 2 above)
Comment (avalluri) [reply pkg/pmem-csi-operator/controller/deployment/controller_driver.go:101]: Okay, added that to the comment.
